backend/urls.py
from django.urls import path
from backend import views

app_name = 'backend'

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('confirm-logout/', views.confirm_logout, name='confirm_logout'),
    path('logout-view/', views.logout_view, name='logout_view'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('pass-form/', views.pass_form, name='pass_form'),
    path('edit-profile-form/', views.edit_profile_form, name='edit_profile_form'),
    path('add-category/', views.categroy_form, name='categroy_form'),
    path('add-post/', views.post_form, name='post_form'),
    path('register-page/', views.register, name='register'),
    path('category-page/', views.view_categories, name='view_categories'),
    path('delete-category/<int:cat_id>/',
         views.delete_category, name='delete_category'),
    path('edit-category/<int:cat_id>/',
         views.edit_category, name='edit_category'),
    path('single-category/<int:cat_id>/',
         views.single_category, name='single_category'),
    path('list-category/',
         views.ListCategories.as_view(), name='list_categories'),
    path('add-category/',
         views.AddCategory.as_view(), name='add_category'),
    path('update-category/<int:pk>/',
         views.UpdateCategory.as_view(), name='up_category'),
]

yemi_project/urls.py
from django.contrib import admin
from django.urls import path, include
from frontend import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('webpages/', include('frontend.urls')),
    path('admin-pages/', include('backend.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.db import models

# Create your models here.

backend/forms.py
from django import forms
from frontend.models import *
from django.core import validators
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm



class Register(UserCreationForm):
    username = forms.CharField(label='Username*', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Username'}))
    email = forms.EmailField(label='Email*',
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email'}))
    first_name = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Firstname'}))
    last_name = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Lastname'}))
    password1 = forms.CharField(label='Enter Password*', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Password'}))
    password2 = forms.CharField(label='Confirm Password*', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Password'}))
    botfield = forms.CharField(required=False, widget=forms.HiddenInput(),
                               validators=[validators.MaxLengthValidator(0)])

    def clean_email(self):
        email_field = self.cleaned_data.get('email')
        if User.objects.filter(email=email_field).exists():
            raise forms.ValidationError('Email already exist')
        return email_field

    class meta():
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
            return user



class CategoryForm(forms.ModelForm):
    cat_name = forms.CharField(label="Category Name*",
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Enter Category'}))
    desc = forms.CharField(label='Description', required=False,
                               widget=forms.Textarea(
                                   attrs={'class': 'form-control'}
                               ))
    catch_bot = forms.CharField(required=False,
                                widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])
    # clean_<fieldname> is use to validate for just one field
    def clean_cat_name(self):
        cat = self.cleaned_data.get('cat_name').lower()
        if Category.objects.filter(cat_name=cat).exists():
            raise forms.ValidationError(f'{cat} already exist')
        return cat

    class Meta():
        fields = '__all__'
        model = Category


class PostForm(forms.ModelForm):
    PUBLISH = 'PB'
    UNPUBLISH = 'UPB'
    FEATURED_VALUES = [
        (PUBLISH, 'Publish'),
        (UNPUBLISH, 'Unpublish')
    ]
    pst_title = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Post Title'})
    )
    featured = forms.CharField(
        widget=forms.Select(
            attrs={'class': 'form-control'}, choices=FEATURED_VALUES)
        
    )

    content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )
    pst_img = forms.ImageField()
    category = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}))
    catch_bot = forms.CharField(required=False,
                                widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

    class Meta():
        exclude = ['created', 'user']
        model = Post

class ChangePassword(PasswordChangeForm):
    old_password = forms.CharField(label='Your Old Password', widget=forms.PasswordInput(
        attrs={'class':'form-control', 'placeholder':'Enter Old Password'}))
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Password'}))
    new_password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[
                                 validators.MaxLengthValidator(0)])


class EditProfileForm(forms.ModelForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}))
    first_name = forms.CharField(label='Firstname', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Firstname'}))
    last_name = forms.CharField(label='Lastname', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Lastname'}))
    email = forms.CharField(label='Email', widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Email', 'disabled':'disabled'}))
    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

backend/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth import update_session_auth_hash

from django.contrib import messages

from django.views.generic import(
    ListView, CreateView, 
    DeleteView, DetailView,
    UpdateView
    )

from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

from backend.forms import *
# Create your views here.


@login_required(login_url='/admin-pages/')
def dashboard(request):
    return render(request, 'backend/index.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('backend:dashboard')
        else:
            messages.error(request, 'Username and Password do not match')
    return render(request, 'frontend/login.html')


@login_required(login_url='/admin-pages/')
def confirm_logout(request):
    return render(request, 'backend/confirm-logout.html')


@login_required(login_url='/admin-pages/')
def logout_view(request):
    logout(request)
    return redirect('backend:login_view')


@login_required(login_url='/admin-pages/')
def categroy_form(request):
    if request.method == 'POST':
        cat_form = CategoryForm(request.POST)
        if cat_form.is_valid():
            cat_form.save()
            messages.success(request, 'Category Created')
    else:
        cat_form = CategoryForm()
    return render(request, 'backend/add-category.html', {'cat': cat_form})


@login_required(login_url='/admin-pages/')
def post_form(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            instance = post_form.save(commit=False)
            instance.user = request.user
            instance.save()
            messages.success(request, 'Post Created')
    else:
        post_form = PostForm()
    return render(request, 'backend/add-post.html', {'post': post_form})


def register(request):
    if request.method == 'POST':
        register = Register(request.POST)
        if register.is_valid():
            register.save()
            messages.success(request, 'User have been registered')
    else:
        register = Register()
    return render(request, 'frontend/register.html', {'reg': register})


@login_required(login_url='/admin-pages/')
def view_categories(request):
    categories = Category.objects.all()
    return render(request, 'backend/view-category.html', {'cat': categories})


@login_required(login_url='/admin-pages/')
def delete_category(request, cat_id):
    delete_cate = Category.objects.get(id=cat_id)
    delete_cate.delete()
    return redirect('backend:view_categories')


@login_required(login_url='/admin-pages/')
def edit_category(request, cat_id):
    single_cat = get_object_or_404(Category, id=cat_id)
    if request.method == 'POST':
        cat_obj = CategoryForm(request.POST, instance=single_cat)
        if cat_obj.is_valid():
            cat_obj.save()
            messages.success(request, 'Category Edited successfully')
    else:
        cat_obj = CategoryForm(instance=single_cat)
    return render(request, 'backend/edit-category.html', {'cat_form':cat_obj})


@login_required(login_url='/admin-pages/')
def single_category(request, cat_id):
    single = get_object_or_404(Category, id=cat_id)
    return render(request, 'backend/single-category.html', {'sin':single})


@login_required(login_url='/admin-pages/')
def pass_form(request):
    if request.method == 'POST':
        pass_form = ChangePassword(data=request.POST, user=request.user)
        if pass_form.is_valid():
            pass_form.save()
            update_session_auth_hash(request, pass_form.user) 
            messages.success(request, 'Password changed successfully.')
    else:
        pass_form = ChangePassword(user=request.user)
    return render(request, 'backend/change-password.html', {'pass_key': pass_form})


@login_required(login_url='/admin-pages/')
def edit_profile_form(request):
    if request.method == 'POST':
        edit_form = EditProfileForm(data=request.POST, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            messages.success(request, 'User edited successfully.')
    else:
        edit_form = EditProfileForm(instance=request.user)
    return render(request, 'backend/edit-profile.html', {'edit': edit_form})


class ListCategories(LoginRequiredMixin, ListView):
    login_url = '/admin-pages/'
    model = Category
    template_name = 'backend/class-category.html'
    context_object_name = 'list_cat'


class AddCategory(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = '/admin-pages/'
    model = Category
    template_name = 'backend/class-add-category.html'
    form_class = CategoryForm
    success_url = reverse_lazy('backend:add_category')
    success_message = 'Category added successfully'


class UpdateCategory(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    login_url = '/admin-pages/'
    model = Category
    template_name = 'backend/class-add-category.html'
    form_class = CategoryForm
    success_url = reverse_lazy('backend:update_category')
    success_message = 'Category updated successfully'

templates/backend/add-category.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Add Category
{% endblock %}

{% block content %}
<h2>Add Category</h2>
<form method="post">
    {% include 'backend/form-snippet.html' with form=cat %}
    <input type="submit" value="Add Category" class="btn btn-primary">
</form>

{% endblock %}

templates/backend/add-post.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Add Post
{% endblock %}

{% block content %}
<h2>Add Post</h2>
<form method="post" enctype="multipart/form-data">
    {% include 'backend/form-snippet.html' with form=post %}
    <input type="submit" value="Add Post" class="btn btn-primary">
</form>

{% endblock %}

templates/backend/admin-sidebar.html
{% load static %}
<div class="col-sm-2 bg-dark h-100 pt-2 bg-warning" id="sideBar">
    <img src="{% static 'backend/images/logo.png' %}" alt="" class="img-fluid">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active text-white" href="#">Add User</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">View Users</a>
        </li>
    
    </ul>
    <hr class="bg-white">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'backend:post_form' %}">Add Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">View Post</a>
        </li>

    </ul>
    <hr class="bg-white">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'backend:categroy_form' %}">Add Category</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'backend:add_category' %}">Add Class Category</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'backend:view_categories' %}">View Category</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'backend:list_categories' %}">List Category</a>
        </li>

    </ul>
    <hr class="bg-white">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'backend:pass_form' %}">Change Password</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">View Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'backend:edit_profile_form' %}">Edit Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'backend:confirm_logout' %}">Logout</a>
        </li>

    </ul>
    <hr class="bg-white">
</div>

templates/backend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'backend/css/bootstrap.min.css' %}">
    <link href="{% static 'backend/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'backend/css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	<div class="container-fluid">
  		<div class="row">
            {% if request.user.is_staff %}
                  {% include 'backend/admin-sidebar.html' %}
            {% else %}
                {% include 'backend/user-sidebar.html' %}
            {% endif %}
  			<div class="col-sm-10">
  				<div class="row">
  					<div class="col-sm-12  pt-4 pb-4" id="topBar">
  						<a class="text-white">
  							<span class="float-right name">{{ request.user.get_full_name }}</span>
  						</a>
  					</div>
                  </div>
                  <div class="row">
                      <div class="col-sm-12">
                         {% block content %}
                         {% endblock %}
                      </div>
                  </div>
  				
  			</div>
  		</div>
  	</div>
    
	<script src="{% static 'backend/js/jquery-3.3.1.slim.min.js' %}"></script>
	<script src="{% static 'backend/js/popper.min.js' %}"></script>
	<script src="{% static 'backend/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/backend/change-password.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Change Password
{% endblock %}

{% block content %}
<h2>Change Password</h2>

<form method="post">
    {% include 'backend/form-snippet.html' with form=pass_key %}
    <input type="submit" value="Change Password" class="btn btn-primary">
</form>

{% endblock %}

templates/backend/class-add-category.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Add Category
{% endblock %}

{% block content %}
{% if not form.instance.pk %}
<h2>Add Category</h2>
{% else %}
<h2>Edit Category</h2>
{% endif %}
<form method="post">
    {% include 'backend/form-snippet.html' with form=form %}
    {% if not form.instance.pk %}
        <input type="submit" value="Add Category" class="btn btn-primary">
    {% else  %}
        <input type="submit" value="Edit Category" class="btn btn-primary">
    {% endif %}
</form>

{% endblock %}

templates/backend/class-category.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
View Category 
{% endblock %}

{% block content %}
<h2>View Category </h2>
<table class="table table-bordered">
    <tr>
        <th>Category Name</th>
        <th>Category Desc</th>
        <th colspan="3">Action</th>
    </tr>
    {% if list_cat %}
        {% for c in list_cat %}
            <tr>
                <td>{{ c.cat_name }}</td>
                <td>{{ c.desc }}</td>
                <td><a href="{% url 'backend:delete_category' c.id %}">Delete</a></td>
                <td><a href="{% url 'backend:up_category' c.id %}">Edit</a></td>
                <td><a href="{% url 'backend:single_category' c.id %}">View</a></td>
            </tr>
        {% endfor %}
    {% endif %}
    <tr>

    </tr>
</table>

{% endblock %}

templates/backend/confirm-logout.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Confirm Logout
{% endblock %}

{% block content %}
<h2>Confirm Logout</h2>
<p>Do really want to logout?</p>
<a href="{% url 'backend:logout_view' %}">logout</a>
{% endblock %}

templates/backend/edit-category.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Edit Category
{% endblock %}

{% block content %}
<h2>Edit Category</h2>

<form method="post">
    {% include 'backend/form-snippet.html' with form=cat_form %}
    <input type="submit" value="Edit Category" class="btn btn-primary">
</form>

{% endblock %}

templates/backend/edit-profile.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
{{ request.user.get_full_name }}
{% endblock %}

{% block content %}
<h2>{{ request.user.get_full_name }}</h2>

<form method="post">
    {% include 'backend/form-snippet.html' with form=edit %}
    <input type="submit" value="Edit Profile" class="btn btn-primary">
</form>

{% endblock %}

templates/backend/form-snippet.html
<!-- SUCCESS MESSAGE STARTS HERE -->
    {% if messages %}
        {% for mes in messages %}
            <div class="alert alert-success">{{ mes }}</div>
        {% endfor %}
    {% endif %}
        <!-- SUCCESS MESSAGE ENDS HERE -->

    {% for hidden in form.hidden_fields %}
        {% if hidden.errors %}
            {% for error in hidden.errors %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
        {% endif %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
        {% endif %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
        </div>
    {% endfor %}
    {% csrf_token %}

templates/backend/index.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
Dashboard
{% endblock %}

{% block content %}
<h2>Dashboard</h2>
{% endblock %}

templates/backend/single-category.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
{{ sin.cat_name }}
{% endblock %}

{% block content %}
<h2>View Category </h2>
<table class="table table-bordered">
    <tr>
        <th>Category Name</th>
        <th>Category Desc</th>
    </tr>
        {% if sin %}
            <tr>
                <td>{{ sin.cat_name }}</td>
                <td>{{ sin.desc }}</td>
            </tr>
        {% endif %}
    <tr>

    </tr>
</table>

{% endblock %}

templates/backend/user-sidebar.html
{% load static %}
<div class="col-sm-2 bg-dark h-100 pt-2 bg-warning" id="sideBar">
    <img src="{% static 'backend/images/logo.png' %}" alt="" class="img-fluid">
    <hr class="bg-white">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'backend:post_form' %}">Add Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">View Post</a>
        </li>

    </ul>
    <hr class="bg-white">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active text-white" href="{% url 'backend:pass_form' %}">Change Password</a>

        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">View Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'backend:edit_profile_form' %}">Edit Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'backend:confirm_logout' %}">Logout</a>
        </li>

    </ul>
    <hr class="bg-white">
</div>