backend/urls.py
from django.urls import path
from backend import views

app_name = 'backend'

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('confirm-logout/', views.confirm_logout, name='confirm_logout'),
    path('logout-view/', views.logout_view, name='logout_view'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('pass-form/', views.pass_form, name='pass_form'),
    path('edit-profile-form/', views.edit_profile_form, name='edit_profile_form'),
    path('add-category/', views.categroy_form, name='categroy_form'),
    path('add-post/', views.post_form, name='post_form'),
    path('register-page/', views.register, name='register'),
    path('category-page/', views.view_categories, name='view_categories'),
    path('delete-category/<int:cat_id>/',
         views.delete_category, name='delete_category'),
    path('edit-category/<int:cat_id>/',
         views.edit_category, name='edit_category'),
    path('single-category/<int:cat_id>/',
         views.single_category, name='single_category'),
    path('list-category/',
         views.ListCategories.as_view(), name='list_categories'),
    path('add-category/',
         views.AddCategory.as_view(), name='add_category'),
    path('update-category/<int:pk>/',
         views.UpdateCategory.as_view(), name='up_category'),
]

frontend/urls.py
from django.urls import path
from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.about, name='about'),
    path('detail-page/<int:abt_id>/', views.about_detail, name='about_detail'),
    path('blog-pages/', views.blog, name='blog'),
    path('users-page/', views.users, name='users'),
    path('single-blog/<int:post_id>/', views.single_blog, name='single_blog'),
    path('post-cat/<int:cat_id>/',
         views.post_from_category, name='post_from_category'),
    path('service-page/', views.services, name='services'),
    path('contact-page/', views.contact, name='contact'),
]

yemi_project/urls.py
from django.contrib import admin
from django.urls import path, include
from frontend import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('webpages/', include('frontend.urls')),
    path('admin-pages/', include('backend.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    cat_name = models.CharField(max_length=100, verbose_name='Category Name')
    desc = models.TextField(blank=True, null=True, verbose_name='Description')

    def __str__(self):
        return self.cat_name

    class Meta():
        verbose_name_plural='Post Category'

class Post(models.Model):
    PUBLISH = 'PB'
    UNPUBLISH = 'UPB'
    FEATURED_VALUES = [
        (PUBLISH, 'Publish'),
        (UNPUBLISH, 'Unpublish')
    ]
    pst_title = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)
    pst_img = models.ImageField(blank=True, null=True, upload_to='uploads/')
    featured = models.CharField(max_length=5, choices=FEATURED_VALUES, default=PUBLISH)
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.pst_title

    class Meta():
        verbose_name_plural = 'Post'

class AboutModel(models.Model):
    abt_title = models.CharField(max_length=100)
    abt_image = models.ImageField(blank=True, null=True, upload_to='uploads/')
    biography = models.TextField()

    def __str__(self):
        return self.abt_title

    class Meta():
        verbose_name_plural = 'About Us'


class ContactModel(models.Model):
    CHOOSE = 'Choose'
    FACEBOOK = 'FB'
    TWITTER = 'TW'
    NAIRALAND = 'NL'
    LINKEDIN = 'LN'
    REFERER_FIELD = [
        (CHOOSE, 'Please Choose'),
        (FACEBOOK, 'Facebook'),
        (TWITTER, 'Twitter'),
        (NAIRALAND, 'Nairaland'),
        (LINKEDIN, 'Linkedin')
    ]

    MALE = 'ML'
    FEMALE = 'FM'
    GENDER_FIELD = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    ]
    name = models.CharField(max_length=150)
    phone_no = models.CharField(max_length=150)
    email = models.EmailField()
    referer = models.CharField(max_length=10, default=CHOOSE, blank=True)
    gender = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.name

frontend/views.py
from django.shortcuts import render
from frontend.models import *
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

# SEND MAIL IMPORTS STARTS HERE
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
# SEND MAIL IMPORTS ENDS HERE

# Create your views here.

def index(request):
    post = Post.objects.order_by('-created')[:3]
    about = AboutModel.objects.all()[:3]
    context = {
        'pt':post,
        'ab':about
    }
    return render(request, 'frontend/index.html', context)

def about(request):
    about = AboutModel.objects.all()
    return render(request, 'frontend/about.html', {'abt':about})

def about_detail(request, abt_id):
    detail = AboutModel.objects.get(id=abt_id)
    return render(request, 'frontend/detail.html', {'det':detail})

def users(request):
    return render(request, 'frontend/users.html')

def blog(request):
    post = Post.objects.all()
    return render(request, 'frontend/post-list.html', {'pst':post})

# The code below displayspost from a category
def post_from_category(request, cat_id):
    count_post_cat = Post.objects.filter(category__id=cat_id).count()
    category = Category.objects.get(id=cat_id)
    post_cat = Post.objects.filter(category__id=cat_id)
    context = {
                'pst': post_cat, 
                'ct': count_post_cat,
                'category':category
                }

    return render(request, 'frontend/post-cat.html', context)

def single_blog(request, post_id):
    try:
        single = Post.objects.get(id=post_id)
    except:
        return render(request, 'frontend/404.html')
    return render(request, 'frontend/single-blog.html', {'sin':single})

def services(request):
    return render(request, 'frontend/services.html')

def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phoneNo')
        email = request.POST.get('email')
        referer = request.POST.get('referer')
        gender = request.POST.get('gender')
        message = request.POST.get('message')
        subject = 'Contact Us Form'
        context = {
            'name':name,
            'phone':phone,
            'email':email,
            'referer':referer,
            'gender':gender,
            'message': message,
        }
        html_message = render_to_string('frontend/mail-template.html', context)
        plain_message = strip_tags(html_message)
        from_email = 'From <lappyng@gmail.com>'
        email_send = mail.send_mail(subject, plain_message, from_email, [
                    'uwazie.benedict@alabiansolutions.com', 'adeloyeadeyemi@gmail.com'], 
                    html_message=html_message)
        save_contact = ContactModel(name=name, phone_no=phone, email=email, referer=referer, gender=gender)
        save_contact.save()
        if email_send:
            messages.success(request, 'Email is sent')
        else:
            messages.error(request, 'Email is not sent')
 
    return render(request, 'frontend/contact.html')

templates/frontend/about.html
{% extends 'frontend/base.html' %}
<!Doctype html>
{% load static %}
{% block title %}
About
{% endblock %}

{% block content %}
<section id="sectionTitle">
  <div class="pageTitle">
    <h1>About Us</h1>
  </div>
</section>
<!-- END OF PAGE TITLE -->
<section id="content">
  <div class="row">
    <div class="col-sm-9 text-center" id="mainContent">
      <div class="row">
        {% if abt %}
          {% for a in abt %}
              <div class="col-sm-4">
                <a href="{% url 'frontend:about_detail' a.id  %}">
                  <img src="{{ a.abt_image.url }}" class="img-circle">
                </a>
                <h2>{{ a.abt_title }}</h2>
                <a href="{% url 'frontend:about_detail' a.id  %}" class="btn btn-primary">Readmore</a>
              </div>
          {% endfor %}
        {% endif %}
        
        
      </div>
    </div>
      {% include 'frontend/sidebar.html' %}

  </div>
</section>
{% endblock %}

templates/frontend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="{% static 'frontend/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
      <header id="siteLogo">
        <div class="row">
          <div class="col-sm-3">
            <a href="index.html">
              <img src="{% static 'frontend/images/logo.png'  %}">
            </a>
          </div>
          <div class="col-sm-9">
            <span class="social-logo pull-right">
              <a href="#">
                <img src="{% static 'frontend/images/fb.png' %}" class="img-circle">
              </a>
              <a href="#">
                <img src="{% static 'frontend/images/tw.png' %}" class="img-circle">
              </a><a href="#">
                <img src="{% static 'frontend/images/gp.png' %}" class="img-circle">
              </a>
            </span>
          </div>
        </div>
      </header>
      <!-- END OF SITE LOGO ROW -->
      <section id="siteMenu">
        <div class="row">
          <nav class="navbar navbar-inverse">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-target="#mainNav" data-toggle="collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="mainNav">
              {% url 'index' as Home %}
              {% url 'frontend:about' as About %}
              {% url 'frontend:users' as Users %}
              {% url 'frontend:blog' as Blog %}
              {% url 'frontend:services' as Services %}
              {% url 'frontend:contact' as Contact %}
              {% url 'backend:login_view' as Login %}
              {% url 'backend:register' as Register %}
              <ul class="nav navbar-nav">
                <li {% if request.path == Home %} class="active" {% endif %}><a href="{% url 'index' %}">Home</a></li>
                <li {% if request.path == About %} class="active" {% endif %}><a href="{% url 'frontend:about' %}">About</a></li>
                <li {% if request.path == Users %} class="active" {% endif %}><a href="{% url 'frontend:users' %}">Users</a></li>
                <li {% if request.path == Blog %} class="active" {% endif %}><a href="{% url 'frontend:blog' %}">Blog</a></li>
                <li {% if request.path == Services %} class="active" {% endif %}><a href="{% url 'frontend:services' %}">Services</a></li>
                <li {% if request.path == Login %} class="active" {% endif %}><a href="{% url 'backend:login_view' %}">Login</a></li>
                <li {% if request.path == Register %} class="active" {% endif %}><a href="{% url 'backend:register' %}">Register</a></li>
                <li {% if request.path == Contact %} class="active" {% endif %}><a href="{% url 'frontend:contact' %}">Contact</a></li>
              </ul>
            </div>
          </nav>
        </div>
      </section>
      <!-- END OF SITE MENU -->
      {% block content %}
      {% endblock %}
    </div>
    <footer class="container-fluid" id="siteFooter">
      <div class="row">
        <div class="col-sm-4">
          <h4>Menu</h4>
          <ul class="nav">
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
        <div class="col-sm-4">
          <h4>Services</h4>
          <ul class="nav">
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Software Development</a></li>
            <li><a href="#">Mobile App Development</a></li>
            <li><a href="#">Training</a></li>
          </ul>
        </div> 
        <div class="col-sm-4">
          <h4>Branches</h4>
          <ul class="nav">
            <li><a href="#">Ikeja</a></li>
            <li><a href="#">Festac</a></li>
            <li><a href="#">Surulere</a></li>
            <li><a href="#">Lekki</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <p>&copy; 2016</p>
        </div>
        <div class="col-md-9">
          <p class="copy pull-right">
            <a href="#" target="_blank">www.alabiansolutions.com</a>
          </p>
        </div>
      </div>
    </footer>

    <script src="{% static 'frontend/js/jquery.js' %}"></script>
    <script src="{% static 'frontend/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/frontend/contact.html
{% extends 'frontend/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block title %}
Contact
{% endblock %}

{% block content %}

      <!-- END OF SITE MENU -->
      <section id="sectionTitle">
        <div class="pageTitle">
          <h1>Contact</h1>
        </div>
      </section>
      <!-- END OF PAGE TITLE -->
      <section id="content">
        <div class="row">
          <div class="col-sm-9 text-center" id="mainContent">
            <div class="row">
              <div class="col-sm-12">
                {% if messages %}
                  {% for mes in messages %}
                      <div class="alert {{mes.tags }}">{{ mes }}</div>
                  {% endfor %}
                {% endif %}
                <form  class="form" method="post">
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <label for="labelUser">Name*</label>
                        <input type="text" required name="name" id="labelUser" placeholder="Your Name" class="form-control">
                      </div>
                    </div>
                    <!-- END OF NAME -->
                   <div class="col-sm-6">
                      <div class="form-group">
                       <label for="labelPhone">Phone No*</label>
                       <input type="text" required name="phoneNo" id="labelPhone" placeholder="Your Phone" class="form-control">
                     </div>
                   </div>
                   <!-- END OF PHONE -->
                  </div>
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <label for="labelEmail">Email</label>
                        <input type="email" name="email" id="labelEmail" class="form-control" placeholder="Your Email">
                      </div>
                    </div>
                    <!-- END OF EMAIL -->
                   <div class="col-sm-6">
                      <div class="form-group">
                       <label for="labelReferer">Referer</label>
                       <select id="labelReferer" class="form-control" name="referer">
                       	 <option value="Facebook">Facebook</option>
                       	 <option value="Twitter">Twitter</option>
                       	 <option value="Instagram">Instagram</option>
                       	 <option value="Nairaland">Nairaland</option>
                         <option value="" selected>Please Choose</option>
                       </select>
                     </div>
                   </div>
                   <!-- END OF REFERER -->
                  </div>
                  <div class="row">
                  	<div class="col-sm-12">
                  		<div class="form-group">
                  			<label>Gender</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  			<label>
                  				<input type="radio" name="gender" value="Male">
                  				Male
                        </label>
                        <label>
                  				<input type="radio" name="gender" value="Female">
                  				Female
                  			</label>
                  		</div>
                  	</div>
                  </div>
                  <!-- END OF GENDER -->
                 
                  <!-- FILE UPLOAD -->
                  <!-- <div class="row">
                    <div class="col-sm-12">
                      <div class="form-group">
                        <label>Upload File</label>
                        <input type="file" name="upload" class="form-control">
                      </div>
                    </div>
                  </div> -->
                  <!-- END OF FILE UPLOAD -->
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="form-group">
                        <label for="labelMessage">Message</label>
                        <textarea name="message" id="labelMessage" class="form-control"> </textarea>
                      </div>
                    </div>
                    <input type="submit" name="send" value="Send" class="btn btn-primary">
                  </div>
                  {% csrf_token %}
                </form>
              </div>
            </div>
          </div>
          {% include 'frontend/sidebar.html' %}
        </div>
      </section>
    {% endblock %}

templates/frontend/detail.html
{% extends 'frontend/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block title %}
Detail
{% endblock %}   

{% block content %}
<!-- END OF SITE MENU -->
      <section id="sectionTitle">
        <div class="pageTitle">
          <h1>{{ det.abt_title }}</h1>
        </div>
      </section>
      <!-- END OF PAGE TITLE -->
      <section id="content">
        <div class="row">
          <div class="col-sm-9 text-center" id="detailContent">
            {% if det %}
              <div class="contain-img">
                <div class="img-div">
                  <img src="{{ det.abt_image.url }}" class="img-responsive">
                </div>
              </div>
              <div class="detail-content">
                <h2>{{ det.abt_title }}</h2>
                <p>
                  {{ det.biography }}
                </p>
              </div>
            {% endif %}
             

          </div>
          <aside class="col-sm-3" id="sideBar">
            <div class="widget">
              <h3>Menu</h3>
              <ul class="nav">
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </div>
            <div class="widget">
              <h3>Branches</h3>
              <ul class="nav">
                <li><a href="#">Ikeja</a></li>
                <li><a href="#">Festac</a></li>
                <li><a href="#">Surulere</a></li>
                <li><a href="#">Lekki</a></li>
              </ul>
            </div>
          </aside>
          <!-- END OF ASIDE CONTENT -->
        </div>
      </section>
   {% endblock %}

templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load static %}
<!Doctype html>
{% block title %}
Home
{% endblock %}

{% block content %}
  <section id="banner">
    <div class="row">
      <div class="col-sm-3 col-sm-offset-9 text-center">
        <div class="caption">
          <h1>Join Us</h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet minus, esse ex molestias maiores. Provident
            nam totam modi, expedita quos sit voluptates distinctio porro illo esse asperiores, animi eveniet ipsam?
          </p>
          <a href="#" class="btn btn-primary">Readmore</a>
        </div>
      </div>
    </div>
  </section>
  <section id="services" class="text-center">
    <div class="page-header">
      <h1>Services</h1>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <span class="fa fa-android"></span>
        <h1>Mobile Development</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat nemo, id expedita at molestias hic odit amet
          officiis laboriosam vero optio inventore dolorum accusantium fugiat accusamus blanditiis ratione, doloribus
          voluptates.
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat nemo, id expedita at molestias hic odit amet
          officiis laboriosam vero optio inventore dolorum accusantium fugiat accusamus blanditiis ratione, doloribus
          voluptates.
        </p>
        <a href="#" class="btn btn-primary">Readmore</a>
      </div>
      <div class="col-sm-4">
        <span class="fa fa-apple"></span>
        <h1>Software Development</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat nemo, id expedita at molestias hic odit amet
          officiis laboriosam vero optio inventore dolorum accusantium fugiat accusamus blanditiis ratione, doloribus
          voluptates.
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat nemo, id expedita at molestias hic odit amet
          officiis laboriosam vero optio inventore dolorum accusantium fugiat accusamus blanditiis ratione, doloribus
          voluptates.
        </p>
        <a href="#" class="btn btn-primary">Readmore</a>
      </div>
      <div class="col-sm-4">
        <span class="fa fa-code"></span>
        <h1>Web Development</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat nemo, id expedita at molestias hic odit amet
          officiis laboriosam vero optio inventore dolorum accusantium fugiat accusamus blanditiis ratione, doloribus
          voluptates.
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat nemo, id expedita at molestias hic odit amet
          officiis laboriosam vero optio inventore dolorum accusantium fugiat accusamus blanditiis ratione, doloribus
          voluptates.
        </p>
        <a href="#" class="btn btn-primary">Readmore</a>
      </div>
    </div>
  </section>
  <section id="post" class="text-center">
    <div class="page-header">
      <h1>Latest Post</h1>
    </div>
    <div class="row">
      {% if pt %}
          {% for p in pt %}
            <div class="col-sm-4">
             <img src="{{ p.pst_img.url }}" class="img-responsive" alt="">
              <h1>{{ p.pst_title }}</h1>
              <p>
                {{ p.content|truncatewords:30 }}
              </p>
              <a href="{% url 'frontend:single_blog' p.id %}" class="btn btn-primary">Readmore</a>
            </div>
          {% endfor %}
      {% endif %}
    </div>
  </section>
  <section id="pub" class="text-center">
    <div class="page-header">
      <h1>Featured Post</h1>
    </div>
    <div class="row">
      {% if pt %}
      {% for p in pt %}
        {% if p.featured == 'PB' %}
          <div class="col-sm-4">
            <img src="{{ p.pst_img.url }}" class="img-responsive" alt="">
            <h1>{{ p.pst_title }}</h1>
            <p>
              {{ p.content|truncatewords:30 }}
            </p>
            <a href="{% url 'frontend:single_blog' p.id %}" class="btn btn-primary">Readmore</a>
          </div>
        {% endif %}
      {% endfor %}
      {% endif %}
    </div>
  </section>
  <!-- END OF SERVICE SECTION -->
{% endblock %}

templates/frontend/login.html
{% extends 'frontend/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block title %}
Contact
{% endblock %}

{% block content %}

      <!-- END OF SITE MENU -->
      <section id="sectionTitle">
        <div class="pageTitle">
          <h1>Login</h1>
        </div>
      </section>
      <!-- END OF PAGE TITLE -->
      <section id="content">
        <div class="row">
          <div class="col-sm-9 text-center" id="mainContent">
            <div class="row">
              <div class="col-sm-12">
                {% if messages %}
                  {% for mes in messages %}
                      <div class="alert {{mes.tags }}">{{ mes }}</div>
                  {% endfor %}
                {% endif %}
                <form  class="form" method="post">
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="form-group">
                        <label for="labelUser">Username*</label>
                        <input type="text" required name="username" id="labelUser" placeholder="Your Username" class="form-control">
                      </div>
                    </div>
                    <!-- END OF NAME -->
                   <div class="col-sm-12">
                      <div class="form-group">
                       <label for="labelPass">Password*</label>
                       <input type="password" required name="password" id="labelPass" placeholder="Your Password" class="form-control">
                     </div>
                   </div>
                   <!-- END OF PHONE -->
                  </div>
                  <input type="submit" value="Login" class="btn btn-primary">
                  {% csrf_token %}
                </form>
              </div>
            </div>
          </div>
          {% include 'frontend/sidebar.html' %}
        </div>
      </section>
    {% endblock %}

templates/frontend/mail-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h2></h2>
    <table width='650' border="1">
        <tr>
            <th>Fields</th>
            <th>Data</th>
        </tr>
        <tr>
            <td>Name</td>
            <td>{{ name }}</td>
        </tr>
        <tr>
            <td>Phone</td>
            <td>{{ phone }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{ email }}</td>
        </tr>
        <tr>
            <td>Referer</td>
            <td>{{ referer }}</td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>{{ gender }}</td>
        </tr>
        <tr>
            <td>Message</td>
            <td>{{ message }}</td>
        </tr>


    </table>
    
</body>
</html>

templates/frontend/post-cat.html
{% extends 'frontend/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block title %}
Post-list 
{% endblock %}

{% block content %}

      <!-- END OF SITE MENU -->
      <section id="sectionTitle">
        <div class="pageTitle">
          <h1>{{ ct }} Post From {{ category.cat_name }} Category</h1>
        </div>
      </section>
      <!-- END OF PAGE TITLE -->
      <section id="content">
        <div class="row">
          <div class="col-sm-9" id="mainContent">
            {% if pst %}
              {% for p in pst %}
                <div class="row">
                  <div class="col-md-4 col-sm-4">
                    <div class="thumbnail">
                      <img src="{{ p.pst_img.url }}">
                    </div>
                  </div>
                  <div class="col-md-8 col-sm-8">
                    <div class="blog-content">
                      <p>
                        Time:{{ p.created }}, 
                        Category:
                        {% for c in p.category.all %}
                            {{ c.cat_name }}
                        {% endfor %}.
                        Posted By: <a href="#">{{ p.user.username }}</a>.
                
                      </p>
                      <h2>{{ p.pst_title }}</h2>
                      <p>
                        {{ p.content|truncatewords:25 }}
                      </p>
                      <a href="{% url 'frontend:single_blog' p.id %}" class="btn btn-success">Readmore</a>
                    </div>
                  </div>
                </div>
              {% endfor %}
            {% endif %}
           
            <!-- END OF BLOG ROW 1 -->
            
          </div>
         {% include 'frontend/sidebar.html' %}
        </div>
      </section>
   {% endblock %}

templates/frontend/post-list.html
{% extends 'frontend/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block title %}
Post-list 
{% endblock %}

{% block content %}

      <!-- END OF SITE MENU -->
      <section id="sectionTitle">
        <div class="pageTitle">
          <h1>5 Post From Sports Category</h1>
        </div>
      </section>
      <!-- END OF PAGE TITLE -->
      <section id="content">
        <div class="row">
          <div class="col-sm-9" id="mainContent">
            {% if pst %}
              {% for p in pst %}
                <div class="row">
                  <div class="col-md-4 col-sm-4">
                    <div class="thumbnail">
                      <img src="{{ p.pst_img.url }}">
                    </div>
                  </div>
                  <div class="col-md-8 col-sm-8">
                    <div class="blog-content">
                      <p>
                        Time:{{ p.created }}, 
                        Category:
                        {% for c in p.category.all %}
                            <!-- This is the url pointing to post category -->
                            <a href="{% url 'frontend:post_from_category' c.id %}">{{ c.cat_name }},</a>
                        {% endfor %}.
                        Posted By: <a href="#">{{ p.user.username }}</a>.
                
                      </p>
                      <h2>{{ p.pst_title }}</h2>
                      <p>
                        {{ p.content|truncatewords:25 }}
                      </p>
                      <a href="{% url 'frontend:single_blog' p.id %}" class="btn btn-success">Readmore</a>
                    </div>
                  </div>
                </div>
              {% endfor %}
            {% endif %}
           
            <!-- END OF BLOG ROW 1 -->
            
          </div>
         {% include 'frontend/sidebar.html' %}
        </div>
      </section>
   {% endblock %}